name: Release
on:
  - push

jobs:
  create-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image
        run: docker build . --tag $IMAGE_NAME
      - name: Login to registry
        run: |
          export CR_PAT=${{ secrets.GHCR }}
          echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
      - name: push Image
        run: |
          docker push ghcr.io/${{ github.actor }}/djang-todo:latest
